server.port=8081
spring.application.name=order-dlt-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=spring_user
spring.datasource.password=spring_secure_password
spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order-dlt-manager-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=com.kafka.order.dlt.dto

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html