spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=spring_user
spring.datasource.password=spring_secure_password

spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=localhost:9092